stages: 
    - test

job_1:
    stage: test
    script:
        - echo "Testing................."
        - echo "////////////////////////" 
        - mkdir -p test/dir/
        - vim test/dir/hello.txt
        - cat "Hello"> test/dir/hello.txt
    before_script:
        - apt-get update && apt-get install -y vim     
    artifacts:
        paths:
            - test/dir/
            - test/dir/hello.txt
    tags:
        - dind        
       