stages: 
    - test

job_1:
    stage: test
    script:
        - echo "Testing................."
        - echo "////////////////////////" 
        - mkdir -p test/dir/
        - touch test/dir/hello.txt
        - echo "Hello"> test/dir/hello.txt     
    artifacts:
        paths:
            - test/dir/
            - test/dir/hello.txt
    tags:
        - dind        
       