stages:
  - build
  - deploy
  - post

image:
  name: hashicorp/terraform:latest
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    
.install_ansible: &install_ansible
  - apt update
  - apt install -y python3
  - apt install -y ansible



terraform_init:
  stage: build
  script:
    - echo "/////////////////////////////"
    - terraform init
    - ls -al
    - terraform validate
    - terraform plan
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
  tags:
    - Docker_Runner
  rules:
    - when: manual   

terraform_apply:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    - apt update && apt install -y wget gnupg unzip lsb-release
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    - apt update
    - apt install -y terraform

  script:
    - *install_ansible
    - terraform apply -auto-approve
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
      - terraform.tfstate
  tags:
    - Docker_Runner
  
terraform_delete:
  stage: post
  script:
    - terraform destroy -auto-approve
  tags:
    - Docker_Runner
  when: manual