stages:
  - build
  - deploy
  - post

image:
  name: hashicorp/terraform:latest
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    
.install_ansible: &install_ansible
  - apk update
  - apk add python3
  - apk add ansible



terraform_init:
  stage: build
  script:
    - ls -a
    - echo "///////////////////////////////"
    - sleep 5
    - terraform init
    - ls -al
    - terraform validate
    - terraform plan
    - ls -a
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
  tags:
    - Docker_Runner
  rules:
    - when: manual   

terraform_apply:
  stage: deploy
  script:
    - *install_ansible
    - terraform apply -auto-approve
    - ls -a
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
      - terraform.tfstate
  tags:
    - Docker_Runner
  
terraform_delete:
  stage: post
  script:
    - terraform destroy -auto-approve
    - ls -a
  tags:
    - Docker_Runner
  when: manual