stages:
  - build
  - test
  - publish
  - deploy
  - post

image:
  name: hashicorp/terraform:latest
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  
.install_bash: &install_bash
  - apk update
  - apk add bash
    
.install_ansible: &install_ansible
  - apk update
  - apk add python3
  - apk add ansible



terraform_init:
  stage: build
  script:
    - echo "////////////////////////////"
    - terraform init
    - ls -al
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
  tags:
    - Docker_Runner
  rules:
    - when: manual   

terraform_validate:
  stage: test
  script:
    - terraform validate
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
  tags:
    - Docker_Runner

terraform_plan:
  stage: publish
  script:
    - terraform plan
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
  tags:
    - Docker_Runner

terraform_apply:
  stage: deploy

  script:
    - *install_bash
    - *install_ansible
    - terraform apply -auto-approve
  artifacts:
    paths:
      - .terraform
      - .terraform.lock.hcl
      - terraform.tfstate
  tags:
    - Docker_Runner
  
terraform_delete:
  stage: post
  script:
    - terraform destroy -auto-approve
  tags:
    - Docker_Runner
  when: manual